branch-defaults:
  master:
    environment: aa-env2
    group_suffix: null
environment-defaults:
  aa-env2:
    branch: null
    repository: null
  test-env:
    branch: null
    repository: null
global:
  application_name: node-express
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
